revise/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('students.urls')),
]

students/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "students"

urlpatterns = [
    
    path('',views.home,name = 'home'),
    path('wayez/',views.wayez_details, name='wayez_details'),
    path('template_wayez/',views.template_wayez, name = 'template'),
    path('form/',views.form,name="form"),

]

students/models.py
from django.db import models

# Create your models here.

class students(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    dept = models.CharField(max_length=50)

    def __str__(self):
        return self.name +" "+ self.dept

    

students/forms.py
from django import forms
from students import models

class student_model_form(forms.ModelForm):
    class Meta:
        model = models.students
        fields = "__all__"

students/views.py
from django.shortcuts import render
from django.http import HttpResponse
from students.models import students
from students import forms

def home(request):
    return HttpResponse("Hello World")


def wayez_details(request):
    return HttpResponse("এপ থেকে বলছি মাগো !!! ")

def template_wayez(request):
    student_list = students.objects.order_by('name')
    diction = {'students': student_list}
    return render(request,'students/index.html',context=diction)

def form(request):
    student_form= forms.student_model_form()

    if request.method == "POST":
        student_form = forms.student_model_form(request.POST)

        if student_form.is_valid():
            student_form.save(commit=True)
            return template_wayez(request)



    diction = {'test_key':student_form}
    return render(request, 'students/form.html', context=diction)

templates/students/form.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form</title>
</head>
<body>
    <form action="" method="POST">
        {{test_key.as_p}}
        {% csrf_token %}

    <input type="Submit">
    </form>
</body>
</html>

templates/students/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Hello</title>
</head>
<body>
    <h1> টেমপ্লেটস থেকে বলছি ভাই !! আমার আর নিস্তার নাই </h1>
    <img src="{% static 'image/mahadi.jpg' %}" alt="">

    <table border="1">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Department</th>
        </tr>
        {% for row in students %}
        <tr>
            <td>{{row.name}}</td>
            <td>{{row.age}}</td>
            <td>{{row.dept}}</td>
        </tr>

        {% endfor %}

    </table>
    <a href="{% url 'students:form' %}">Add New Student</a>
</body>
</html>